import type { DividendEvent, EarningsEvent, EconomicEvent } from "@/providers";
import type { CalendarAvailability, CalendarEventType, MarketCalendarAnalysis, MarketCalendarEvent } from "@/types";

function stableId(value: string) { let hash = 5381; for (const character of value) hash = Math.imul(hash, 33) ^ character.charCodeAt(0); return `event-${(hash >>> 0).toString(16)}`; }
function impact(value: string | null): MarketCalendarEvent["importance"] { const normalized = value?.toLowerCase() ?? ""; return normalized.includes("high") ? "HIGH" : normalized.includes("medium") ? "MEDIUM" : "LOW"; }
function availability(status: boolean, provider: string | null, reason: string | null): CalendarAvailability { return { status: status ? "AVAILABLE" : "UNAVAILABLE", provider, reason }; }

export function composeCalendarAnalysis(input: { from: string; to: string; earnings?: { data: EarningsEvent[]; provider: string } | null; dividends?: { data: DividendEvent[]; provider: string } | null; macro?: { data: EconomicEvent[]; provider: string } | null; errors?: Partial<Record<CalendarEventType, string>> }): MarketCalendarAnalysis {
  const events: MarketCalendarEvent[] = [
    ...(input.earnings?.data.map((event) => ({ id: stableId(`earnings:${event.symbol}:${event.date}`), type: "EARNINGS" as const, title: `${event.symbol} earnings`, date: event.date.slice(0, 10), time: event.time, symbol: event.symbol, country: null, importance: "HIGH" as const, provider: input.earnings!.provider, estimate: event.estimatedEps, actual: event.actualEps, previous: null, unit: "EPS", details: { estimatedRevenue: event.estimatedRevenue, actualRevenue: event.actualRevenue, currency: event.currency } })) ?? []),
    ...(input.dividends?.data.map((event) => ({ id: stableId(`dividend:${event.symbol}:${event.date}`), type: "DIVIDEND" as const, title: `${event.symbol} ex-dividend`, date: event.date.slice(0, 10), time: null, symbol: event.symbol, country: null, importance: "MEDIUM" as const, provider: input.dividends!.provider, estimate: event.adjustedAmount ?? event.amount, actual: null, previous: null, unit: event.currency, details: { recordDate: event.recordDate, paymentDate: event.paymentDate, declarationDate: event.declarationDate, yield: event.yield, frequency: event.frequency } })) ?? []),
    ...(input.macro?.data.map((event) => ({ id: stableId(`macro:${event.country}:${event.event}:${event.date}`), type: "MACRO" as const, title: event.event, date: event.date.slice(0, 10), time: event.date.includes("T") ? event.date.slice(11, 16) : null, symbol: null, country: event.country, importance: impact(event.impact), provider: input.macro!.provider, estimate: event.estimate, actual: event.actual, previous: event.previous, unit: event.unit ?? event.currency, details: { currency: event.currency, impact: event.impact } })) ?? []),
  ];
  const unique = [...new Map(events.map((event) => [event.id, event])).values()].filter((event) => event.date >= input.from && event.date <= input.to).sort((a, b) => `${a.date}${a.time ?? ""}`.localeCompare(`${b.date}${b.time ?? ""}`));
  return { from: input.from, to: input.to, monthLabel: new Intl.DateTimeFormat("en-US", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${input.from}T00:00:00Z`)), events: unique, availability: { EARNINGS: availability(Boolean(input.earnings), input.earnings?.provider ?? null, input.errors?.EARNINGS ?? null), DIVIDEND: availability(Boolean(input.dividends), input.dividends?.provider ?? null, input.errors?.DIVIDEND ?? null), MACRO: availability(Boolean(input.macro), input.macro?.provider ?? null, input.errors?.MACRO ?? null) }, persisted: false, calculatedAt: new Date().toISOString() };
}
