import "server-only";

import { eq } from "drizzle-orm";
import { getDatabase, isDatabaseConfigured, politicalFilings, politicalSyncStates, politicalTransactions, politicians } from "@/db";
import { ensureInstrument } from "@/services/account/instrument-repository";
import type { PoliticalTransaction, Politician } from "@/types";

const numeric = (value: number | null) => value === null ? null : String(value);

export async function persistPoliticalTransactions(input: { transactions: PoliticalTransaction[]; politicians: Politician[]; houseRecords: number; senateRecords: number; duplicatesRemoved: number }) {
  if (!isDatabaseConfigured()) return { persisted: false, transactions: 0, mapped: 0, unresolved: input.transactions.filter((row) => row.resolutionStatus === "UNRESOLVED_ASSET").length };
  const database = getDatabase(); const instrumentsBySymbol = new Map<string, Awaited<ReturnType<typeof ensureInstrument>>>(); let stored = 0; let mapped = 0;
  for (const politician of input.politicians) await database.insert(politicians).values({ id: politician.id, normalizedName: politician.normalizedName, displayName: politician.displayName, chamber: politician.chamber, party: politician.party, state: politician.state, district: politician.district, activeStatus: politician.activeStatus, sourceIdentifiers: politician.sourceIdentifiers }).onConflictDoUpdate({ target: politicians.id, set: { displayName: politician.displayName, chamber: politician.chamber, party: politician.party, state: politician.state, district: politician.district, sourceIdentifiers: politician.sourceIdentifiers, updatedAt: new Date() } });
  for (const transaction of input.transactions) {
    let instrument = transaction.symbol ? instrumentsBySymbol.get(transaction.symbol) : undefined;
    if (!instrument && transaction.symbol && transaction.resolutionStatus === "RESOLVED") { instrument = await ensureInstrument({ symbol: transaction.symbol, name: transaction.assetName, type: "EQUITY" }).catch(() => undefined); if (instrument) instrumentsBySymbol.set(transaction.symbol, instrument); }
    let filingId: string | null = null;
    const filingSourceId = transaction.filingId ?? transaction.sourceId;
    const [filing] = await database.insert(politicalFilings).values({ politicianId: transaction.politicianId, provider: transaction.provider, sourceId: filingSourceId, filingType: transaction.filingType, disclosureDate: new Date(`${transaction.disclosureDate}T00:00:00Z`), sourceUrl: transaction.sourceUrl, amendment: transaction.amendment, fetchedAt: new Date(transaction.fetchedAt), payload: { sourceId: transaction.sourceId } }).onConflictDoUpdate({ target: [politicalFilings.provider, politicalFilings.sourceId], set: { sourceUrl: transaction.sourceUrl, amendment: transaction.amendment, fetchedAt: new Date(transaction.fetchedAt), updatedAt: new Date() } }).returning({ id: politicalFilings.id });
    filingId = filing?.id ?? (await database.select({ id: politicalFilings.id }).from(politicalFilings).where(eq(politicalFilings.sourceId, filingSourceId)).limit(1))[0]?.id ?? null;
    const values = { sourceId: transaction.sourceId, fingerprint: transaction.fingerprint, politicianId: transaction.politicianId, filingId, instrumentId: instrument?.id ?? null, canonicalIssuerId: instrument?.issuerId ?? null, chamber: transaction.chamber, party: transaction.party, state: transaction.state, district: transaction.district, ownerType: transaction.ownerType, assetName: transaction.assetName, assetType: transaction.assetType, rawTicker: transaction.rawTicker, symbol: transaction.symbol, sector: transaction.sector, transactionType: transaction.transactionType, transactionDate: new Date(`${transaction.transactionDate}T00:00:00Z`), disclosureDate: new Date(`${transaction.disclosureDate}T00:00:00Z`), marketAvailableDate: new Date(`${transaction.marketAvailableDate}T00:00:00Z`), disclosureDelayDays: transaction.disclosureDelayDays, amountMin: numeric(transaction.amountMin), amountMax: numeric(transaction.amountMax), amountRangeRaw: transaction.amountRangeRaw, estimatedAmount: numeric(transaction.estimatedAmount), amountMethod: transaction.amountMethod, priceAtTransaction: numeric(transaction.priceAtTransaction), priceAtDisclosure: numeric(transaction.priceAtDisclosure), currentPrice: numeric(transaction.currentPrice), sharesEstimate: numeric(transaction.sharesEstimate), source: transaction.source, sourceUrl: transaction.sourceUrl, filingType: transaction.filingType, provider: transaction.provider, fetchedAt: new Date(transaction.fetchedAt), verified: transaction.verified, verificationStatus: transaction.verificationStatus, resolutionStatus: transaction.resolutionStatus, amendment: transaction.amendment, rawPayload: { normalizedId: transaction.id } };
    const inserted = await database.insert(politicalTransactions).values(values).onConflictDoUpdate({ target: politicalTransactions.fingerprint, set: { ...values, updatedAt: new Date() } }).returning({ id: politicalTransactions.id });
    if (inserted.length) stored += 1; if (instrument) mapped += 1;
  }
  const latest = input.transactions.map((row) => row.disclosureDate).sort().at(-1); const unresolved = input.transactions.filter((row) => row.resolutionStatus === "UNRESOLVED_ASSET").length;
  await database.insert(politicalSyncStates).values({ key: "fmp-congressional", lastSuccessfulSync: new Date(), houseRecords: input.houseRecords, senateRecords: input.senateRecords, mappedInstruments: mapped, unresolvedAssets: unresolved, duplicatesRemoved: input.duplicatesRemoved, latestDisclosure: latest ? new Date(`${latest}T00:00:00Z`) : null, providerStatus: "OK", metadata: { normalizedRecords: input.transactions.length } }).onConflictDoUpdate({ target: politicalSyncStates.key, set: { lastSuccessfulSync: new Date(), houseRecords: input.houseRecords, senateRecords: input.senateRecords, mappedInstruments: mapped, unresolvedAssets: unresolved, duplicatesRemoved: input.duplicatesRemoved, latestDisclosure: latest ? new Date(`${latest}T00:00:00Z`) : null, providerStatus: "OK", metadata: { normalizedRecords: input.transactions.length }, updatedAt: new Date() } });
  return { persisted: true, transactions: stored, mapped, unresolved };
}

export async function getPoliticalSyncHealth() {
  if (!isDatabaseConfigured()) return { databaseConfigured: false, lastSync: null, houseRecords: 0, senateRecords: 0, mappedInstruments: 0, unresolvedAssets: 0, duplicatesRemoved: 0, latestDisclosure: null, fmpStatus: "RUNTIME_ONLY" };
  const row = (await getDatabase().select().from(politicalSyncStates).where(eq(politicalSyncStates.key, "fmp-congressional")).limit(1))[0];
  return { databaseConfigured: true, lastSync: row?.lastSuccessfulSync?.toISOString() ?? null, houseRecords: row?.houseRecords ?? 0, senateRecords: row?.senateRecords ?? 0, mappedInstruments: row?.mappedInstruments ?? 0, unresolvedAssets: row?.unresolvedAssets ?? 0, duplicatesRemoved: row?.duplicatesRemoved ?? 0, latestDisclosure: row?.latestDisclosure?.toISOString() ?? null, fmpStatus: row?.providerStatus ?? "NOT_SYNCED" };
}
