import { Activity, BarChart3, Bitcoin, CalendarDays, Gauge, Newspaper, ShieldAlert, Target } from "lucide-react";
import { formatCompactNumber, formatCurrency, formatPercent } from "@/lib";
import type { AssetIntelligenceReport } from "@/types";

const unavailable = "Dato non disponibile";
const number = (value: number | null, digits = 2) => value === null ? unavailable : value.toFixed(digits);
const money = (value: number | null, currency: string) => value === null ? unavailable : formatCurrency(value, currency);
function Metric({ label, value, note }: { label: string; value: React.ReactNode; note?: string }) { return <div className="ci-metric"><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</div>; }
function Section({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="ci-section"><div className="ci-section-body"><div className="mb-5 flex items-center gap-3"><span className="ci-section-icon">{icon}</span><h2 className="text-xl font-bold">{title}</h2></div>{children}</div></section>; }

export function AssetIntelligenceView({ report }: { report: AssetIntelligenceReport }) {
  const title = `${report.kind} INTELLIGENCE`;
  return <div className="container-shell ci-page"><section className="ci-summary"><div className="ci-summary-copy"><span className="insight-badge">{report.kind === "CRYPTO" ? <Bitcoin size={14}/> : <BarChart3 size={14}/>} {title}</span><h1>{report.symbol}</h1><p>{report.name} · analisi quantitativa basata su dati di mercato reali. Nessun fondamentale societario viene applicato a questo strumento.</p><div className="ci-summary-meta"><span>{report.exchange}</span><span>{report.marketState}</span><span>{report.provider}</span><span>{report.freshnessType.replaceAll("_", " ")}</span></div></div><div className="ci-gauge" style={{ "--score": `${report.technical?.score ?? 0}%` } as React.CSSProperties}><div><strong>{report.technical?.score.toFixed(0) ?? "—"}</strong><span>/100</span></div><small>TECHNICAL SCORE</small></div><div className="ci-summary-side"><Metric label="Prezzo" value={money(report.price, report.currency)}/><Metric label="Variazione" value={formatPercent(report.changePercent, true)}/><Metric label="Volume" value={report.volume === null ? unavailable : formatCompactNumber(report.volume)}/><Metric label="Aggiornato" value={report.sourceTimestamp ? new Date(report.sourceTimestamp).toLocaleString() : unavailable}/></div></section>
  <Section title="Trend, momentum e liquidità" icon={<Activity size={18}/>}><div className="ci-metric-grid"><Metric label="Trend" value={report.technical?.trend ?? unavailable}/><Metric label="RSI 14" value={number(report.technical?.rsi ?? null)}/><Metric label="MACD" value={number(report.technical?.macd ?? null, 4)}/><Metric label="SMA 20" value={money(report.technical?.sma20 ?? null, report.currency)}/><Metric label="SMA 50" value={money(report.technical?.sma50 ?? null, report.currency)}/><Metric label="SMA 200" value={money(report.technical?.sma200 ?? null, report.currency)}/><Metric label="Volume relativo" value={number(report.technical?.relativeVolume ?? null)}/><Metric label="Market cap" value={report.marketCap === null ? unavailable : formatCompactNumber(report.marketCap)}/></div></Section>
  <Section title="Rischio, regime e correlazioni" icon={<Gauge size={18}/>}><div className="ci-metric-grid"><Metric label="Volatilità annualizzata" value={report.technical?.volatility === null || report.technical?.volatility === undefined ? unavailable : formatPercent(report.technical.volatility * 100, false)}/><Metric label="Maximum drawdown" value={report.technical?.drawdown === null || report.technical?.drawdown === undefined ? unavailable : formatPercent(report.technical.drawdown * 100, false)}/><Metric label="Supporto" value={money(report.technical?.support ?? null, report.currency)}/><Metric label="Resistenza" value={money(report.technical?.resistance ?? null, report.currency)}/><Metric label="Correlazione Bitcoin" value={number(report.correlations.bitcoin)}/><Metric label="Correlazione Nasdaq" value={number(report.correlations.nasdaq)}/></div></Section>
  <Section title="Forecast probabilistico e livelli operativi" icon={<Target size={18}/>}><div className="ci-metric-grid"><Metric label="Bear · P10" value={money(report.forecast?.bear ?? null, report.currency)}/><Metric label="Base · P50" value={money(report.forecast?.base ?? null, report.currency)}/><Metric label="Bull · P90" value={money(report.forecast?.bull ?? null, report.currency)}/><Metric label="Probabilità rialzo" value={report.forecast ? formatPercent(report.forecast.probabilityUp * 100, false) : unavailable}/><Metric label="Target tecnico" value={money(report.forecast?.target ?? null, report.currency)}/><Metric label="Invalidazione" value={money(report.forecast?.invalidation ?? null, report.currency)}/><Metric label="Confidenza" value={report.forecast ? formatPercent(report.forecast.confidence * 100, false) : unavailable}/><Metric label="Orizzonte" value={report.forecast?.horizon ?? unavailable}/></div><p className="muted mt-4 text-xs">Scenari probabilistici calcolati da distribuzioni storiche; non sono promesse né consulenza personalizzata.</p></Section>
  <Section title="Stagionalità" icon={<CalendarDays size={18}/>}><div className="ci-metric-grid"><Metric label="Qualità" value={report.seasonality?.quality ?? unavailable}/><Metric label="Anni disponibili" value={report.seasonality?.years ?? unavailable}/><Metric label="Mese storicamente migliore" value={report.seasonality?.bestMonth ?? unavailable}/><Metric label="Mese storicamente peggiore" value={report.seasonality?.worstMonth ?? unavailable}/></div></Section>
  <Section title="News e sentiment attribuito" icon={<Newspaper size={18}/>}><div className="ci-metric-grid"><Metric label="Sentiment score" value={number(report.sentiment.score)}/><Metric label="Positive" value={report.sentiment.positive}/><Metric label="Neutral" value={report.sentiment.neutral}/><Metric label="Negative" value={report.sentiment.negative}/><Metric label="Provider" value={report.sentiment.provider ?? unavailable}/></div></Section>
  {report.assetProfile && <Section title={report.kind === "CRYPTO" ? "Fondamentali crypto" : "Profilo ETF"} icon={<BarChart3 size={18}/>}><div className="ci-metric-grid">{report.kind === "CRYPTO" ? <><Metric label="Market cap rank" value={report.assetProfile.marketCapRank ?? unavailable}/><Metric label="Circulating supply" value={report.assetProfile.circulatingSupply === null ? unavailable : formatCompactNumber(report.assetProfile.circulatingSupply)}/><Metric label="Total supply" value={report.assetProfile.totalSupply === null ? unavailable : formatCompactNumber(report.assetProfile.totalSupply)}/><Metric label="Max supply" value={report.assetProfile.maxSupply === null ? unavailable : formatCompactNumber(report.assetProfile.maxSupply)}/><Metric label="All-time high" value={money(report.assetProfile.allTimeHigh, report.currency)} note={report.assetProfile.allTimeHighDate ?? undefined}/><Metric label="BTC dominance" value={report.globalContext?.bitcoinDominance === null || report.globalContext?.bitcoinDominance === undefined ? unavailable : `${report.globalContext.bitcoinDominance.toFixed(1)}%`}/></> : <><Metric label="AUM" value={report.assetProfile.assetsUnderManagement === null ? unavailable : formatCompactNumber(report.assetProfile.assetsUnderManagement)}/><Metric label="Expense ratio" value={report.assetProfile.expenseRatio === null ? unavailable : `${report.assetProfile.expenseRatio.toFixed(2)}%`}/><Metric label="NAV" value={money(report.assetProfile.nav, report.currency)}/><Metric label="Holdings" value={report.assetProfile.holdingsCount ?? unavailable}/></>}</div>{report.assetProfile.topHoldings.length > 0 && <div className="ci-table-wrap mt-5"><table className="ci-table"><thead><tr><th>Holding</th><th>Symbol</th><th>Peso</th></tr></thead><tbody>{report.assetProfile.topHoldings.map((holding) => <tr key={`${holding.name}-${holding.symbol}`}><td>{holding.name}</td><td>{holding.symbol ?? unavailable}</td><td>{holding.weight === null ? unavailable : `${holding.weight.toFixed(2)}%`}</td></tr>)}</tbody></table></div>}<p className="muted mt-4 text-xs">Fonte strutturale: {report.assetProfile.provider}.</p></Section>}
  {report.unavailable.length > 0 && <Section title="Limiti dei dati" icon={<ShieldAlert size={18}/>}><ul className="ci-list negative-list">{report.unavailable.map((item) => <li key={item}>{item}</li>)}</ul></Section>}<p className="muted pb-10 text-xs">Calcolato {new Date(report.calculatedAt).toLocaleString()} · provider quote {report.provider} · fonte {report.sourceTimestamp ?? unavailable}</p></div>;
}
