"use client";

import { useMemo, useState } from "react";
import { CalendarClock, ChevronLeft, ChevronRight, DatabaseZap } from "lucide-react";
import type { CalendarEventType, MarketCalendarAnalysis } from "@/types";
import { DataError, DataUnavailable } from "./data-state";

const eventTypes: CalendarEventType[] = ["EARNINGS", "DIVIDEND", "MACRO"];
const filters: Array<CalendarEventType | "ALL"> = ["ALL", ...eventTypes];
function iso(date: Date) { return date.toISOString().slice(0, 10); }
function monthRange(date: Date) { return { from: iso(new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), 1))), to: iso(new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth() + 1, 0))) }; }

export function CalendarView({ initial }: { initial: MarketCalendarAnalysis }) {
  const [data, setData] = useState(initial); const [filter, setFilter] = useState<CalendarEventType | "ALL">("ALL");
  const [selected, setSelected] = useState(initial.from); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const selectedEvents = useMemo(() => data.events.filter((event) => event.date === selected && (filter === "ALL" || event.type === filter)), [data, selected, filter]);
  const calendarStart = new Date(`${data.from}T00:00:00Z`); const daysInMonth = new Date(Date.UTC(calendarStart.getUTCFullYear(), calendarStart.getUTCMonth() + 1, 0)).getUTCDate(); const leading = (calendarStart.getUTCDay() + 6) % 7;
  const nextEvent = data.events.find((event) => `${event.date}T${event.time ?? "23:59"}:00Z` >= new Date().toISOString());
  async function moveMonth(delta: number) { setLoading(true); setError(null); const next = new Date(Date.UTC(calendarStart.getUTCFullYear(), calendarStart.getUTCMonth() + delta, 1)); const range = monthRange(next); try { const response = await fetch(`/api/calendar?from=${range.from}&to=${range.to}`); const body = await response.json() as { data?: MarketCalendarAnalysis; error?: { message?: string } }; if (!response.ok || !body.data) throw new Error(body.error?.message ?? "Calendar unavailable"); setData(body.data); setSelected(range.from); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Calendar unavailable"); } finally { setLoading(false); } }
  return <div className="container-shell page-stack"><header className="section-row"><div><span className="page-kicker">Workspace / Sourced events</span><h1 className="page-title">Market calendar.</h1><p className="muted mt-3">{data.monthLabel} · earnings, dividends and macro releases</p></div><div className="flex items-center gap-2"><button className="icon-button" onClick={() => void moveMonth(-1)} disabled={loading}><ChevronLeft/></button><button className="icon-button" onClick={() => void moveMonth(1)} disabled={loading}><ChevronRight/></button></div></header>
    {error && <DataError message={error}/>}<div className="grid-3">{eventTypes.map((type) => { const item = data.availability[type]; const count = data.events.filter((event) => event.type === type).length; return <div className="soft-card flex items-center gap-3 p-4" key={type}><DatabaseZap className={item.status === "AVAILABLE" ? "text-emerald-500" : "text-amber-500"} size={18}/><span><strong>{type} · {count}</strong><small className="muted block">{item.status === "AVAILABLE" ? `${item.provider} · ${nextEvent?.type === type ? `next ${nextEvent.date}` : "UTC"}` : item.reason}</small></span></div>; })}</div>
    <nav className="segmented">{filters.map((item) => <button className={filter === item ? "active" : ""} onClick={() => setFilter(item)} key={item}>{item}</button>)}</nav>
    <section className={`calendar-grid grid grid-cols-7 overflow-hidden ${loading ? "opacity-50" : ""}`}>{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <div className="calendar-day-label p-3 text-center font-bold" key={day}>{day}</div>)}{Array.from({ length: leading }, (_, index) => <div className="calendar-cell min-h-28 bg-slate-50" key={`blank-${index}`}/>)}{Array.from({ length: daysInMonth }, (_, index) => { const day = index + 1; const date = iso(new Date(Date.UTC(calendarStart.getUTCFullYear(), calendarStart.getUTCMonth(), day))); const events = data.events.filter((event) => event.date === date && (filter === "ALL" || event.type === filter)); return <button onClick={() => setSelected(date)} key={date} className={`calendar-cell min-h-28 p-3 text-left ${selected === date ? "selected" : ""}`}><strong>{day}</strong><div className="mt-4 flex flex-wrap gap-1">{events.slice(0, 3).map((event) => <span title={event.title} className={`h-2.5 w-2.5 rounded-full ${event.type === "EARNINGS" ? "bg-indigo-500" : event.type === "DIVIDEND" ? "bg-emerald-500" : "bg-amber-500"}`} key={event.id}/>)}</div>{events.length ? <small className="muted mt-2 block">{events.length} events</small> : null}</button>; })}</section>
    <section className="event-detail soft-card p-6"><div className="event-icon"><CalendarClock size={18}/></div><div className="w-full"><span className="small-label">Selected day · {new Date(`${selected}T00:00:00Z`).toLocaleDateString("en-US", { dateStyle: "long", timeZone: "UTC" })}</span>{selectedEvents.length ? <div className="mt-4 grid gap-4">{selectedEvents.map((event) => <div className="border-t border-slate-200 pt-4 first:border-0 first:pt-0" key={event.id}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">{event.title}</h2><span className="badge bg-indigo-50 text-indigo-700">{event.type} · {event.importance}</span></div><p className="muted mt-2">{event.company ?? event.country ?? "Global"} · {event.time ?? "time N/D"} {event.time ? event.timezone : ""} · provider {event.provider}</p><p className="muted mt-1 text-sm">Estimate {event.estimate ?? "N/D"} · Actual {event.actual ?? "N/D"} · Previous {event.previous ?? "N/D"} {event.unit ?? ""}</p></div>)}</div> : <DataUnavailable title="No sourced events" detail="No event from an available provider matches this day and filter."/>}</div></section><p className="muted text-xs">Last updated {new Date(data.calculatedAt).toLocaleString()} · timezone UTC · Persistence: {data.persisted ? "PostgreSQL" : "request cache only"}. Categories marked unavailable are never replaced with demo events.</p></div>;
}
