"use client";

import { useState } from "react";
import { DatabaseZap, Play, RefreshCw } from "lucide-react";

type Health = { overall: string; database: string; datasets: Array<{ dataset: string; status: string; recordCount: number | null; coverage: number | null; calculatedAt: string | null; hasLastKnownGood: boolean; anomalies: string[] }>; runs: Array<{ id: string; jobName: string; provider: string | null; status: string; startedAt: string; fetched: number; inserted: number; errors: number }> };
const jobs = ["economic", "calendar", "political", "cftc", "news", "global-risk"] as const;

export function DataIngestionAdmin({ initial }: { initial: Health }) {
  const [health, setHealth] = useState(initial); const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  async function refresh() { const response = await fetch("/api/admin/data-ingestion", { cache: "no-store" }); const body = await response.json() as { data?: Health; error?: { message?: string } }; if (!response.ok || !body.data) throw new Error(body.error?.message ?? "Health unavailable"); setHealth(body.data); }
  async function run(job: typeof jobs[number]) { setBusy(job); setMessage(null); try { const response = await fetch("/api/admin/data-ingestion", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ job }) }); const body = await response.json() as { data?: { status?: string }; error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? "Job failed"); setMessage(`${job}: ${body.data?.status ?? "completed"}`); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Job failed"); } finally { setBusy(null); } }
  return <div className="container-shell page-stack"><header className="section-row"><div><span className="page-kicker">Preferences / Data operations</span><h1 className="page-title">Data ingestion.</h1><p className="muted mt-3">Persistent datasets, last-known-good state and manual, lock-protected jobs.</p></div><button className="button-outline" onClick={() => void refresh()}><RefreshCw size={16}/>Refresh</button></header>{message && <section className="soft-card p-4"><strong>{message}</strong></section>}<section className="grid-3"><article className="soft-card p-5"><DatabaseZap/><strong className="mt-3 block">Database {health.database}</strong><small className="muted">Overall {health.overall}</small></article>{health.datasets.map((item) => <article className="soft-card p-5" key={item.dataset}><span className="small-label">{item.dataset}</span><strong className="mt-2 block">{item.status}</strong><small className="muted">{item.recordCount ?? "—"} records · coverage {item.coverage?.toFixed(0) ?? "—"}% · LKG {item.hasLastKnownGood ? "YES" : "NO"}</small></article>)}</section><section className="card p-6"><h2 className="text-xl font-bold">Manual run</h2><p className="muted mt-2 text-sm">Runs are rate-limited, idempotent and protected by distributed locks.</p><div className="mt-5 flex flex-wrap gap-3">{jobs.map((job) => <button className="button-outline" disabled={Boolean(busy)} onClick={() => void run(job)} key={job}><Play size={15}/>{busy === job ? "Running…" : job}</button>)}</div></section><section className="card overflow-hidden"><div className="ci-table-wrap"><table className="ci-table"><thead><tr><th>Job</th><th>Status</th><th>Started</th><th>Fetched</th><th>Inserted</th><th>Errors</th></tr></thead><tbody>{health.runs.length ? health.runs.map((run) => <tr key={run.id}><td>{run.jobName}<small>{run.provider ?? "internal"}</small></td><td>{run.status}</td><td>{new Date(run.startedAt).toLocaleString()}</td><td>{run.fetched}</td><td>{run.inserted}</td><td>{run.errors}</td></tr>) : <tr><td colSpan={6}>No persisted runs yet.</td></tr>}</tbody></table></div></section></div>;
}
