import Link from "next/link";
import { Activity, AlertTriangle, ArrowDownRight, ArrowUpRight, CheckCircle2, Clock3, Database, Gauge, Globe2, Info, Layers3, Radio, ShieldCheck, TrendingDown, TrendingUp } from "lucide-react";
import { hasEditorialDivergence, type GlobalRiskHistoryPoint, type GlobalRiskSnapshot } from "@/engines/global-risk";
import type { GlobalMarketBrief } from "@/types";
import { GlobalRiskHistoryChart } from "@/components/charts/global-risk-chart";
import { GlobalMarketsPrintActions, GlobalRiskRefreshButton } from "./global-risk-controls";

function dateTime(value: string | null) { return value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit", timeZone: "Europe/Rome", timeZoneName: "short" }).format(new Date(value)) : "Unavailable"; }
function age(value: string | null, renderedAt: number) { if (!value) return "Unavailable"; const minutes = Math.max(0, Math.floor((renderedAt - new Date(value).getTime()) / 60_000)); return minutes < 60 ? `${minutes}m ago` : minutes < 1_440 ? `${Math.floor(minutes / 60)}h ago` : `${Math.floor(minutes / 1_440)}d ago`; }
function pct(value: number | null) { return value === null ? "—" : `${value >= 0 ? "+" : ""}${value.toFixed(2)}%`; }
function scoreTone(score: number | null) { return score === null ? "unknown" : score < 25 ? "green" : score < 50 ? "yellow" : score < 75 ? "orange" : "red"; }

function ComponentCard({ component }: { component: GlobalRiskSnapshot["components"][number] }) { return <article className="gr-component-card"><header><span className={`gr-score-dot ${scoreTone(component.score)}`}/><div><strong>{component.label}</strong><small>{component.classification} · {component.confidence.replaceAll("_", " ")}</small></div><b>{component.score === null ? "—" : Math.round(component.score)}</b></header><div className="gr-component-bar"><i style={{ width: `${component.score ?? 0}%` }}/></div><p>{component.summary}</p><div className="gr-metric-list">{component.metrics.map((item) => <div key={item.key}><span>{item.label}<small>{item.dataType.replaceAll("_", " ")}</small></span><strong>{item.displayValue}</strong></div>)}</div><footer><span>Sources</span>{component.sources.length ? component.sources.join(" · ") : "Unavailable"}</footer></article>; }

function EditorialBrief({ brief, automaticStatus, renderedAt }: { brief: GlobalMarketBrief | null; automaticStatus: GlobalRiskSnapshot["status"]; renderedAt: number }) {
  if (!brief) return <section className="gr-editorial empty"><div><span className="page-kicker">Editorial market brief</span><h2>No published editorial brief</h2><p>The automatic quantitative monitor remains available. An authenticated editor can paste, parse, preview and publish the scheduled ChatGPT report.</p></div><Link href="/preferences/global-market-brief" className="button-outline">Open brief editor</Link></section>;
  const hours = brief.publishedAt ? (renderedAt - new Date(brief.publishedAt).getTime()) / 3_600_000 : 0; const stale = hours > 48 ? "STALE" : hours > 24 ? "AGING" : null; const divergence = hasEditorialDivergence(automaticStatus, brief.status);
  const visible = [["Volatility", "volatility"], ["Credit", "credit"], ["Liquidity", "liquidity"], ["Rates", "rates"], ["Market breadth", "marketBreadth"], ["Cross-asset", "crossAsset"], ["Macro", "macro"], ["Geopolitics", "geopolitics"], ["Main risks", "mainRisks"], ["Stabilizing factors", "stabilizingFactors"], ["Escalation triggers", "escalationTriggers"], ["Final view", "finalView"]] as const;
  return <section className="gr-editorial"><header><div><span className="page-kicker">Global market brief</span><h2>{brief.title}</h2><p className="gr-source-label">{brief.sourceLabel}</p></div><GlobalMarketsPrintActions/></header>{divergence && <div className="gr-divergence"><AlertTriangle/><div><strong>Divergence detected</strong><p>Automatic model: <b>{automaticStatus}</b> · Editorial brief: <b>{brief.status}</b>. Both assessments are shown without automatic reconciliation.</p></div></div>}<div className="gr-editorial-meta"><span className={`risk-pill ${brief.status.toLowerCase()}`}>{brief.status}</span><span>Systemic stress <b>{brief.systemicStress}</b></span><span>Trend <b>{brief.riskTrend.replaceAll("_", " ")}</b></span><span>Version <b>{brief.version}</b></span><span>Published <b>{age(brief.publishedAt, renderedAt)}</b></span>{stale && <span className="editorial-stale">Editorial brief {stale}</span>}</div><div className="gr-editorial-summary"><span>Summary</span><p>{brief.sections.summary}</p></div><div className="gr-accordion">{visible.map(([label, key], index) => <details key={key} open={index < 2 || key === "finalView"}><summary><strong>{label}</strong><span>{brief.sections[key] === "Not provided." ? "Not provided" : "View section"}</span></summary><p>{brief.sections[key]}</p></details>)}</div><footer><span>Report date {dateTime(brief.reportDate)}</span><Link href="/preferences/global-market-brief">Manage editions →</Link></footer></section>;
}

export function GlobalMarketsView({ snapshot, history, brief, renderedAt }: { snapshot: GlobalRiskSnapshot; history: GlobalRiskHistoryPoint[]; brief: GlobalMarketBrief | null; renderedAt: number }) {
  const changePositive = (snapshot.change ?? 0) > 0;
  return <div className="container-shell gr-page"><header className={`gr-hero ${snapshot.status.toLowerCase()}`}><div className="gr-hero-copy"><span className="gr-live-label"><Radio size={13}/>Automatic Kairo data · {snapshot.dataStatus.replaceAll("_", " ")}</span><div className="gr-title-row"><Globe2/><div><span>Global market risk</span><h1>{snapshot.dataStatus === "SOURCE_UNAVAILABLE" ? "DATA UNAVAILABLE" : `${snapshot.status} ALERT`}</h1></div></div><p>{snapshot.dataStatus === "SOURCE_UNAVAILABLE" ? "No risk regime is asserted because no usable data layer is available." : snapshot.summary.shortSummary}</p><div className="gr-hero-meta"><span><Clock3/>Calculated {dateTime(snapshot.calculatedAt)}</span><span><Database/>{snapshot.activeLayers} active data layers</span><span><Activity/>{snapshot.confidence.replaceAll("_", " ")} confidence</span></div></div><div className="gr-hero-score"><span>Global stress score</span><strong>{snapshot.dataStatus === "SOURCE_UNAVAILABLE" ? "—" : snapshot.score}<small>/100</small></strong><div className="gr-score-track"><i style={{ width: `${snapshot.dataStatus === "SOURCE_UNAVAILABLE" ? 0 : snapshot.score}%` }}/></div><details><summary><Info size={13}/>How is this calculated?</summary><div>{snapshot.components.map((component) => <span key={component.key}>{component.label} <b>{Math.round(component.weight * 100)}%</b></span>)}<small>{snapshot.modelVersion} · {snapshot.dataCompleteness}% coverage</small></div></details></div><div className="gr-hero-systemic"><span>Systemic stress</span><strong>{snapshot.dataStatus === "SOURCE_UNAVAILABLE" ? "UNAVAILABLE" : snapshot.systemicStress}</strong><p>{snapshot.summary.stabilitySummary}</p><div><span>Trend <b>{snapshot.trend.replaceAll("_", " ")}</b></span><span>Previous <b>{snapshot.previousStatus ?? "—"} {snapshot.previousScore ?? ""}</b></span><span>Change <b className={changePositive ? "negative" : "positive"}>{snapshot.change === null ? "—" : `${snapshot.change > 0 ? "+" : ""}${snapshot.change}`}</b></span></div></div></header>

  <div className="gr-toolbar"><div><span>Model {snapshot.modelVersion} · direct {snapshot.rawDirectCoverage}% · calculated from direct {snapshot.calculatedFromDirectCoverage}% · proxy {snapshot.proxyShare}% · stale layers {snapshot.staleLayers}</span><b>Data coverage {snapshot.dataCompleteness}%</b></div><GlobalRiskRefreshButton/></div>

  <section className="gr-regime-grid"><article><Gauge/><span>Market regime</span><strong>{snapshot.status}</strong><p>{snapshot.summary.headline}</p></article><article><ShieldCheck/><span>Systemic monitor</span><strong>{snapshot.systemicStress}</strong><p>{snapshot.summary.stabilitySummary}</p></article><article>{snapshot.trend === "IMPROVING" ? <TrendingDown/> : <TrendingUp/>}<span>Stress trend</span><strong>{snapshot.trend.replaceAll("_", " ")}</strong><p>Uses 1D, 5D and 20D stored observations when available.</p></article><article><Layers3/><span>Data quality</span><strong>{snapshot.confidence.replaceAll("_", " ")}</strong><p>{snapshot.dataCompleteness}% weighted input completeness.</p></article></section>

  <section><div className="gr-section-heading"><div><span className="page-kicker">Quantitative monitor</span><h2>Independent stress blocks</h2></div><p>Missing inputs reduce completeness and are never treated as zero stress.</p></div><div className="gr-components">{snapshot.components.map((component) => <ComponentCard key={component.key} component={component}/>)}</div></section>

  <section className="gr-table-section"><div className="gr-section-heading"><div><span className="page-kicker">Equity stress</span><h2>Global equity markets</h2></div><p>Daily moves, medium-term structure and risk statistics.</p></div><div className="gr-table-wrap"><table><thead><tr><th>Market</th><th>Price</th><th>1D</th><th>5D</th><th>1M</th><th>52W DD</th><th>SMA50</th><th>SMA200</th><th>RSI</th><th>Vol</th></tr></thead><tbody>{snapshot.equityMarkets.map((row) => <tr key={row.symbol}><td><b>{row.name}</b><small>{row.symbol} · {row.source}</small></td><td>{row.price?.toFixed(2) ?? "—"}</td><td className={(row.oneDay ?? 0) >= 0 ? "positive" : "negative"}>{pct(row.oneDay)}</td><td>{pct(row.fiveDay)}</td><td>{pct(row.oneMonth)}</td><td>{pct(row.drawdown52Week)}</td><td>{row.sma50?.toFixed(2) ?? "—"}</td><td>{row.sma200?.toFixed(2) ?? "—"}</td><td>{row.rsi14?.toFixed(1) ?? "—"}</td><td>{pct(row.volatility)}</td></tr>)}</tbody></table></div></section>

  <section className="gr-table-section"><div className="gr-section-heading"><div><span className="page-kicker">Cross-asset monitor</span><h2>Transmission map</h2></div><p>Proxy instruments are explicitly labelled and never presented as direct benchmarks.</p></div><div className="gr-cross-grid">{snapshot.crossAssets.map((row) => <article key={row.symbol}><header><span>{row.name}<small>{row.symbol}</small></span><strong>{row.price?.toLocaleString("en-US", { maximumFractionDigits: 2 }) ?? "—"}</strong></header><div><span>1D <b className={(row.oneDay ?? 0) >= 0 ? "positive" : "negative"}>{pct(row.oneDay)}</b></span><span>5D <b>{pct(row.fiveDay)}</b></span><span>1M <b>{pct(row.oneMonth)}</b></span><span>Vol <b>{pct(row.volatility)}</b></span></div><footer><span>{row.trend}</span><b>Stress {row.stressContribution?.toFixed(0) ?? "—"}</b></footer></article>)}</div></section>

  <section className="gr-driver-grid"><article><div className="gr-section-heading"><div><span className="page-kicker">Risk drivers</span><h2>Top contributors</h2></div></div><ol className="gr-driver-list">{snapshot.riskDrivers.map((driver, index) => <li key={driver.component}><span>{index + 1}</span><div><strong>{driver.component}</strong><small>Score {driver.score.toFixed(0)} · Change {driver.change === null ? "—" : driver.change.toFixed(1)}</small></div><b>{driver.contribution.toFixed(1)} pts</b></li>)}</ol></article><article><div className="gr-section-heading"><div><span className="page-kicker">Stabilizing factors</span><h2>Contained signals</h2></div></div><ul className="gr-stability-list">{snapshot.stabilizingFactors.length ? snapshot.stabilizingFactors.map((factor) => <li key={factor}><CheckCircle2/>{factor}</li>) : <li><Info/>No component currently qualifies as a strong stabilizing factor.</li>}</ul></article></section>

  <section className="gr-trigger-section"><div className="gr-section-heading"><div><span className="page-kicker">Regime conditions</span><h2>Triggers that would change the alert</h2></div><p>All thresholds come from the versioned model configuration.</p></div><div className="gr-trigger-grid"><article><header><ArrowUpRight/>What would escalate the alert?</header>{snapshot.escalationTriggers.map((trigger) => <div key={trigger.id} className={trigger.active ? "active" : ""}><span>{trigger.label}<small>{trigger.threshold}</small></span><b>{trigger.active ? "ACTIVE" : "MONITOR"}</b></div>)}</article><article><header><ArrowDownRight/>What would de-escalate the alert?</header>{snapshot.deEscalationTriggers.map((trigger) => <div key={trigger.id} className={trigger.active ? "active improve" : ""}><span>{trigger.label}<small>{trigger.threshold}</small></span><b>{trigger.active ? "MET" : "PENDING"}</b></div>)}</article></div></section>

  <EditorialBrief brief={brief} automaticStatus={snapshot.status} renderedAt={renderedAt}/>

  <section className="gr-history-section"><div className="gr-section-heading"><div><span className="page-kicker">Historical alert timeline</span><h2>Global stress score</h2></div><p>Regime bands and change markers use stored snapshots; model versions remain attached to their original observations.</p></div><GlobalRiskHistoryChart initialData={history}/></section>

  <section className="gr-sources"><div><span className="page-kicker">Data sources / last update</span><h2>Provenance and freshness</h2></div><div>{snapshot.sources.map((source) => <article key={`${source.category}-${source.provider}`}><span>{source.category}</span><strong>{source.provider}</strong><small>{source.available ? `${source.freshness} · ${dateTime(source.asOf)}` : "Unavailable — confidence reduced"}</small></article>)}</div><footer>Market risk indicators and editorial analysis are informational models and should not be interpreted as guarantees of future market behavior.</footer></section>
  </div>;
}
