"use client";

import { Archive, Clipboard, Copy, Eye, FilePlus2, Save, Send } from "lucide-react";
import { useState } from "react";
import { GLOBAL_MARKET_BRIEF_TEMPLATE } from "@/services/editorial/global-market-brief-parser";
import type { EditorialSectionKey, GlobalMarketBrief, GlobalMarketBriefInput, ParsedGlobalMarketBrief } from "@/types";

const sections: Array<[EditorialSectionKey, string]> = [["summary", "Summary"], ["volatility", "Volatility"], ["credit", "Credit"], ["liquidity", "Liquidity"], ["rates", "Rates"], ["marketBreadth", "Market breadth"], ["crossAsset", "Cross-asset"], ["macro", "Macro"], ["geopolitics", "Geopolitics"], ["mainRisks", "Main risks"], ["stabilizingFactors", "Stabilizing factors"], ["escalationTriggers", "Escalation triggers"], ["finalView", "Final view"]];
const emptyParsed: ParsedGlobalMarketBrief = { status: "UNAVAILABLE", systemicStress: "UNAVAILABLE", riskTrend: "UNAVAILABLE", sections: Object.fromEntries(sections.map(([key]) => [key, "Not provided."])) as ParsedGlobalMarketBrief["sections"], missingSections: sections.map(([key]) => key) };
type Envelope<T> = { data?: T; error?: { message?: string } };
function localDate() { const now = new Date(); return new Date(now.getTime() - now.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }

export function GlobalMarketBriefEditor({ initialHistory }: { initialHistory: GlobalMarketBrief[] }) {
  const [title, setTitle] = useState("Global markets — scheduled market brief"); const [reportDate, setReportDate] = useState(localDate()); const [rawText, setRawText] = useState(""); const [parsed, setParsed] = useState(emptyParsed); const [history, setHistory] = useState(initialHistory); const [preview, setPreview] = useState(false); const [selected, setSelected] = useState<GlobalMarketBrief | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const changeParsed = <K extends keyof ParsedGlobalMarketBrief>(key: K, value: ParsedGlobalMarketBrief[K]) => { setParsed((current) => ({ ...current, [key]: value })); setPreview(false); };
  const payload = (): GlobalMarketBriefInput => ({ title, reportDate: new Date(reportDate).toISOString(), rawText, ...parsed });
  async function parse() { setBusy(true); setMessage(""); try { const response = await fetch("/api/global-market-brief/parse", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rawText }) }); const body = await response.json() as Envelope<ParsedGlobalMarketBrief>; if (!response.ok || !body.data) throw new Error(body.error?.message ?? "Unable to parse report"); setParsed(body.data); setPreview(false); setMessage(`Parsed. ${body.data.missingSections.length} section(s) not provided.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to parse report"); } finally { setBusy(false); } }
  async function persist(mode: "draft" | "publish") { if (mode === "publish" && !preview) { setMessage("Preview the report before publishing."); return; } setBusy(true); setMessage(""); try { const response = await fetch(`/api/global-market-brief/${mode}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload()) }); const body = await response.json() as Envelope<GlobalMarketBrief>; if (!response.ok || !body.data) throw new Error(body.error?.message ?? `Unable to ${mode}`); setHistory((current) => [body.data!, ...current]); setMessage(mode === "publish" ? `Published version ${body.data.version}.` : `Draft version ${body.data.version} saved.`); } catch (error) { setMessage(error instanceof Error ? error.message : `Unable to ${mode}`); } finally { setBusy(false); } }
  function duplicate(item: GlobalMarketBrief) { setTitle(`${item.title} — copy`); setReportDate(localDate()); setRawText(item.rawText); setParsed({ status: item.status, systemicStress: item.systemicStress, riskTrend: item.riskTrend, sections: item.sections, missingSections: item.missingSections }); setPreview(false); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function archive(item: GlobalMarketBrief) { setBusy(true); try { const response = await fetch(`/api/global-market-brief/${item.id}/archive`, { method: "POST" }); if (!response.ok) { const body = await response.json() as Envelope<never>; throw new Error(body.error?.message ?? "Unable to archive"); } setHistory((current) => current.map((entry) => entry.id === item.id ? { ...entry, state: "ARCHIVED" } : entry)); setMessage(`Version ${item.version} archived.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to archive"); } finally { setBusy(false); } }
  return <div className="container-shell gbe-page"><header><div><span className="page-kicker">Private editorial workflow</span><h1 className="page-title">New global market brief</h1><p>Paste a scheduled ChatGPT report, parse it deterministically, edit every field, preview and publish a versioned edition.</p></div><button className="button-outline" onClick={() => void navigator.clipboard.writeText(GLOBAL_MARKET_BRIEF_TEMPLATE)}><Clipboard size={16}/>Copy ChatGPT template</button></header>
  <section className="gbe-workflow"><span className="active">1 Paste</span><span className={parsed.status !== "UNAVAILABLE" ? "active" : ""}>2 Parse & edit</span><span className={preview ? "active" : ""}>3 Preview</span><span>4 Publish</span></section>
  <section className="card gbe-raw"><div className="gbe-fields"><label>Title<input value={title} maxLength={240} onChange={(event) => { setTitle(event.target.value); setPreview(false); }}/></label><label>Report date<input type="datetime-local" value={reportDate} onChange={(event) => { setReportDate(event.target.value); setPreview(false); }}/></label></div><label>Raw report <small>Plain text only · maximum 100 KB</small><textarea value={rawText} onChange={(event) => { setRawText(event.target.value); setPreview(false); }} placeholder="PASTE CHATGPT REPORT HERE" rows={18}/></label><div className="gbe-actions"><button className="button-primary" disabled={busy || !rawText.trim()} onClick={() => void parse()}><FilePlus2 size={16}/>Parse report</button><button className="button-soft" disabled={busy} onClick={() => void persist("draft")}><Save size={16}/>Save draft</button></div></section>
  <section className="card gbe-edit"><div><span className="page-kicker">Structured fields</span><h2>Edit parsed report</h2></div><div className="gbe-fields three"><label>Status<select value={parsed.status} onChange={(event) => changeParsed("status", event.target.value as ParsedGlobalMarketBrief["status"])}>{["UNAVAILABLE", "GREEN", "YELLOW", "ORANGE", "RED"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Systemic stress<select value={parsed.systemicStress} onChange={(event) => changeParsed("systemicStress", event.target.value as ParsedGlobalMarketBrief["systemicStress"])}>{["UNAVAILABLE", "NONE", "WATCH", "ELEVATED", "ACTIVE"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Risk trend<select value={parsed.riskTrend} onChange={(event) => changeParsed("riskTrend", event.target.value as ParsedGlobalMarketBrief["riskTrend"])}>{["UNAVAILABLE", "IMPROVING", "STABLE", "DETERIORATING", "RAPIDLY_DETERIORATING"].map((value) => <option key={value}>{value}</option>)}</select></label></div><div className="gbe-section-fields">{sections.map(([key, label]) => <label key={key}>{label}<textarea rows={4} value={parsed.sections[key]} onChange={(event) => { changeParsed("sections", { ...parsed.sections, [key]: event.target.value }); }}/></label>)}</div><div className="gbe-actions"><button className="button-outline" onClick={() => setPreview(true)}><Eye size={16}/>Preview</button><button className="button-primary" disabled={busy || !preview} onClick={() => void persist("publish")}><Send size={16}/>Publish new version</button>{message && <span className="gbe-message">{message}</span>}</div></section>
  {preview && <section className={`gbe-preview ${parsed.status.toLowerCase()}`}><header><span>Preview — exactly as public editorial content</span><h2>{title}</h2><div><b>{parsed.status}</b><span>Systemic {parsed.systemicStress}</span><span>{parsed.riskTrend.replaceAll("_", " ")}</span></div></header><article><span>Summary</span><p>{parsed.sections.summary}</p></article><div>{sections.filter(([key]) => key !== "summary").map(([key, label]) => <article key={key}><span>{label}</span><p>{parsed.sections[key]}</p></article>)}</div><footer>CHATGPT SCHEDULED ANALYSIS — MANUALLY PUBLISHED</footer></section>}
  <section className="card gbe-history"><div><span className="page-kicker">Published briefs and drafts</span><h2>Version history</h2></div><div className="gr-table-wrap"><table><thead><tr><th>Report</th><th>Status</th><th>Systemic stress</th><th>Version</th><th>State</th><th>Published</th><th>Actions</th></tr></thead><tbody>{history.map((item) => <tr key={item.id}><td><b>{item.title}</b><small>{new Date(item.reportDate).toLocaleDateString("en-GB")}</small></td><td>{item.status}</td><td>{item.systemicStress}</td><td>v{item.version}</td><td>{item.state}</td><td>{item.publishedAt ? new Date(item.publishedAt).toLocaleString("en-GB") : "—"}</td><td><span className="gbe-row-actions"><button onClick={() => setSelected(item)}><Eye/>View</button><button onClick={() => duplicate(item)}><Copy/>Duplicate</button>{item.state !== "ARCHIVED" && <button onClick={() => void archive(item)}><Archive/>Archive</button>}</span></td></tr>)}</tbody></table></div>{!history.length && <p className="muted">No versions published yet.</p>}{selected && <div className="gbe-version-view"><button onClick={() => setSelected(null)}>Close</button><h3>{selected.title} · v{selected.version}</h3><pre>{selected.rawText}</pre></div>}</section>
  </div>;
}
