"use client";

import { ArrowLeft, ArrowRight, ExternalLink } from "lucide-react";
import { useState } from "react";
import type { NewsData } from "@/types";
import { DataUnavailable } from "./data-state";

export function NewsView({ data }: { data: NewsData }) {
  const [slide, setSlide] = useState(0);
  return <div className="container-shell page-stack">{data.recaps.length ? <section><div className="insight-hero p-6 text-white md:p-10"><div className="flex items-center justify-between gap-4"><span className="insight-badge">Kairo Lens · News briefing</span><button className="button-outline !border-white/20 !bg-white/10 !text-white"><span className="hidden sm:inline">Open briefing</span><ExternalLink size={18}/></button></div><p className="mt-8 max-w-5xl text-xl leading-relaxed md:text-2xl">{data.recaps[slide]}</p></div><div className="mt-5 flex justify-center gap-3"><button className="icon-button" onClick={() => setSlide((slide + data.recaps.length - 1) % data.recaps.length)}><ArrowLeft/></button><div className="flex items-center gap-2">{data.recaps.map((_, index) => <button aria-label={`Recap ${index + 1}`} className={`h-2 w-6 rounded-full border-0 ${slide === index ? "bg-[var(--accent)]" : "bg-slate-300"}`} key={index} onClick={() => setSlide(index)}/>)}</div><button className="icon-button" onClick={() => setSlide((slide + 1) % data.recaps.length)}><ArrowRight/></button></div></section> : <DataUnavailable title="Editorial recap unavailable" detail="Yahoo Finance supplies article metadata, not a generated editorial summary."/>}<section className="grid-2">{data.articles.map((article) => <article className="news-card soft-card p-6" key={article.id}><span className="page-kicker">{article.source} · {article.date}</span><h2 className="mt-5 text-2xl font-bold leading-tight">{article.title}</h2><div className="mt-10 flex items-center justify-between muted"><span>Yahoo Finance news metadata</span>{article.url ? <a className="icon-button !h-9 !w-9" href={article.url} target="_blank" rel="noreferrer" aria-label="Open source"><ExternalLink size={17}/></a> : <span className="muted">Unavailable</span>}</div></article>)}</section>{!data.articles.length && <DataUnavailable title="No news available" detail="No supported Yahoo Finance news items were returned for this symbol."/>}</div>;
}
