"use client";

import { useState } from "react";
import Link from "next/link";
import { BarChart3, Clock3, Download, Landmark, Scale, Users } from "lucide-react";
import type { PoliticalIntelligenceReport, PoliticalPeriod } from "@/types";
import { PoliticalPriceDisclosureChart, PoliticalTimelineChart } from "@/components/charts/political-intelligence-charts";
import { PoliticalClusterList, PoliticalRanking, PoliticalScoreCard, PoliticalTransactionTable, activityRange, politicalMoney } from "./political-intelligence-shared";
import { PoliticalEmptyState } from "./political-empty-state";

const periods: PoliticalPeriod[] = ["7D", "30D", "90D", "6M", "1Y", "3Y", "5Y", "MAX"];

export function PoliticalCompanyIntelligenceView({ initialReport }: { initialReport: PoliticalIntelligenceReport }) {
  const [report, setReport] = useState(initialReport); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function changePeriod(period: PoliticalPeriod) { setLoading(true); setError(null); try { const response = await fetch(`/api/political-intelligence?symbol=${encodeURIComponent(report.symbol ?? "")}&period=${period}&pageSize=20`); const body = await response.json() as { data?: PoliticalIntelligenceReport; error?: { message?: string } }; if (!response.ok || !body.data) throw new Error(body.error?.message ?? "Political data unavailable"); setReport(body.data); } catch (caught) { setError(caught instanceof Error ? caught.message : "Political data unavailable"); } finally { setLoading(false); } }
  const summary = report.summary;
  const insufficient = summary.direction === "INSUFFICIENT_DATA";
  const rangeValue = (min: number, max: number) => insufficient ? "—" : activityRange(min, max);
  const midpointValue = (value: number) => insufficient ? "No verified disclosure data" : `Midpoint ${politicalMoney(value)}`;
  return <div className="container-shell ci-page"><header className="section-row"><div><span className="page-kicker">Alternative data / Congressional disclosures</span><h1 className="page-title">Political Intelligence.</h1><p className="muted mt-3">Public financial disclosures only. Transaction and disclosure dates remain explicitly separate.</p></div><div className="flex flex-wrap gap-2"><a className="button-outline" href={`/api/political-intelligence?symbol=${encodeURIComponent(report.symbol ?? "")}&period=${report.period}&format=csv`}><Download size={16}/>Export CSV</a></div></header><nav className="segmented flex-wrap" aria-label="Political activity period">{periods.map((period) => <button key={period} className={report.period === period ? "active" : ""} disabled={loading} onClick={() => void changePeriod(period)}>{period}</button>)}</nav>{error && <div className="soft-card p-4 negative">{error}</div>}<section className="soft-card p-5"><div className="section-row"><div><span className="small-label">Dataset result</span><strong className="mt-1 block">{report.dataStatus.replaceAll("_", " ")}</strong></div><span className={`badge ${report.dataStatus === "HAS_ACTIVITY" || report.dataStatus === "VERIFIED_ZERO" ? "badge-buy" : "badge-hold"}`}>{report.coverage.historyCoveragePercent.toFixed(0)}% history</span></div><p className="muted mt-2 text-sm">{report.coverage.reason}</p><p className="muted mt-2 text-xs">Window {report.coverage.requestedFrom ?? "earliest available"} → {report.coverage.requestedTo} · stored {report.coverage.historyFrom ?? "—"} → {report.coverage.historyTo ?? "—"} · issuer mapping {report.coverage.mappingRate.toFixed(1)}% · {report.coverage.ingestedRecords} ingested records.</p>{report.coverage.suggestedPeriod && <button className="button-outline mt-4" onClick={() => void changePeriod(report.coverage.suggestedPeriod!)}>Check {report.coverage.suggestedPeriod} coverage</button>}</section>{report.dataStatus !== "HAS_ACTIVITY" ? <PoliticalEmptyState report={report} onSelectPeriod={(period) => void changePeriod(period)}/> : <><PoliticalScoreCard summary={summary}/>
    <section className="grid-3"><article className="metric-card mint"><Landmark/><div><span className="small-label">Purchase range</span><div className="kpi mt-3">{rangeValue(summary.purchaseMin, summary.purchaseMax)}</div><small className="muted">{midpointValue(summary.estimatedPurchaseValue)}</small></div></article><article className="metric-card violet"><Scale/><div><span className="small-label">Sale range</span><div className="kpi mt-3">{rangeValue(summary.saleMin, summary.saleMax)}</div><small className="muted">{midpointValue(summary.estimatedSaleValue)}</small></div></article><article className="metric-card amber"><Clock3/><div><span className="small-label">Disclosure delay</span><div className="kpi mt-3">{summary.medianDisclosureDelay === null ? "—" : `${summary.medianDisclosureDelay.toFixed(0)} days`}</div><small className="muted">P25 {summary.delayP25?.toFixed(0) ?? "—"} · P75 {summary.delayP75?.toFixed(0) ?? "—"} · P90 {summary.delayP90?.toFixed(0) ?? "—"}</small></div></article></section>
    <section className="card p-6"><div className="section-row"><div><span className="section-pill"><BarChart3 size={14}/>Price and disclosure markers</span><p className="muted mt-2 text-sm">T = underlying transaction date. D = public disclosure date and first market-available date used by Kairo.</p></div></div>{report.priceHistory.length ? <PoliticalPriceDisclosureChart prices={report.priceHistory} transactions={report.transactions}/> : <p className="muted p-8">Price history unavailable for this instrument.</p>}</section>
    <section className="grid-2"><div className="card p-6"><h2 className="text-xl font-bold">House vs Senate</h2><div className="ci-metric-grid mt-5">{report.chamberBreakdown.map((row) => <div className="ci-metric" key={row.key}><span>{row.label}</span><strong>{row.purchaseCount} / {row.saleCount}</strong><small>Purchases / sales · {row.uniquePoliticians} members</small></div>)}</div></div><div className="card p-6"><h2 className="text-xl font-bold">Cluster activity</h2><div className="ci-metric-grid mt-5"><div className="ci-metric"><span>Purchase cluster</span><strong>{summary.clusterBuying}</strong></div><div className="ci-metric"><span>Sale cluster</span><strong>{summary.clusterSelling}</strong></div><div className="ci-metric"><span>Direction score</span><strong>{summary.directionScore.toFixed(0)}</strong></div><div className="ci-metric"><span>Momentum score</span><strong>{summary.momentumScore.toFixed(0)}</strong></div></div></div></section>
    <section className="card p-6"><h2 className="flex items-center gap-2 text-xl font-bold"><BarChart3 size={18}/>Disclosure timeline</h2><PoliticalTimelineChart data={report.timeline}/></section>
    <section className="card p-6"><div className="section-row"><div><span className="section-pill"><Landmark size={14}/>Recent public disclosures</span><p className="muted mt-2">Amounts preserve statutory ranges; midpoint estimates are labeled.</p></div><span className="muted">{insufficient ? "No verified disclosure data" : `${report.totalTransactions} records`}</span></div><PoliticalTransactionTable transactions={report.transactions}/></section>
    <section className="grid-2"><PoliticalRanking title="Member activity" rows={report.politicianBreakdown}/><div className="card p-6"><h2 className="text-lg font-bold">Independent clusters</h2><div className="mt-5"><PoliticalClusterList clusters={report.clusters}/></div></div></section>
    <section className="grid-2"><PoliticalRanking title="Most purchased assets" rows={report.mostPurchased}/><PoliticalRanking title="Most sold assets" rows={report.mostSold}/></section>
    <section className="card p-6"><h2 className="text-xl font-bold">Post-disclosure performance</h2><p className="muted mt-2 text-sm">Measured from the first daily market observation on or after the disclosure date, never the transaction date.</p><div className="mt-5 overflow-x-auto"><table className="data-table"><thead><tr><th>Disclosure</th><th>Member</th><th>1D</th><th>5D</th><th>20D</th><th>60D</th><th>120D</th><th>Relative 20D</th><th>Classification</th></tr></thead><tbody>{report.performances.slice(0, 20).map((performance) => { const transaction = report.transactions.find((row) => row.id === performance.transactionId); const value = (item: number | null) => item === null ? "—" : `${item >= 0 ? "+" : ""}${item.toFixed(1)}%`; return <tr key={performance.transactionId}><td>{performance.marketAvailableDate}</td><td>{transaction?.politicianName ?? "—"}</td><td>{value(performance.returns["1D"])}</td><td>{value(performance.returns["5D"])}</td><td>{value(performance.returns["20D"])}</td><td>{value(performance.returns["60D"])}</td><td>{value(performance.returns["120D"])}</td><td>{value(performance.relativeReturns["20D"])}</td><td>{performance.classification}</td></tr>; })}</tbody></table></div><p className="muted mt-5 text-xs">Past post-disclosure performance does not imply future performance.</p></section>
    </>}<section className="grid-2"><div className="card p-6"><h2 className="flex items-center gap-2 text-xl font-bold"><Users size={18}/>Data sources</h2>{report.sources.length ? report.sources.map((source) => <div className="soft-card mt-4 p-4" key={source.label}><strong>{source.label}</strong><small className="muted block">{source.verificationStatus.replaceAll("_", " ")} · fetched {new Date(source.fetchedAt).toLocaleString()}</small></div>) : <p className="muted mt-4 text-sm">No source returned attributable records. This is not presented as activity or as a verified zero.</p>}</div><div className="card p-6"><h2 className="text-xl font-bold">Limitations</h2><ul className="ci-list mt-4">{report.limitations.map((item) => <li key={item}>{item}</li>)}</ul>{report.unresolvedAssets.length > 0 && <Link className="button-outline mt-5 inline-flex" href="/political-intelligence?unresolved=true">Review {report.unresolvedAssets.length} unresolved assets</Link>}</div></section>
  </div>;
}
