import Link from "next/link";
import { formatCompactNumber } from "@/lib";
import type { PoliticalActivitySummary, PoliticalBreakdownRow, PoliticalCluster, PoliticalTransaction } from "@/types";

export const politicalMoney = (value: number) => `$${formatCompactNumber(value)}`;
export const activityRange = (min: number, max: number) => `${politicalMoney(min)} – ${politicalMoney(max)}`;
export const directionClass = (direction: string) => direction.includes("BUYING") ? "badge-buy" : direction.includes("SELLING") ? "badge-sell" : "badge-hold";
const politicalProviderLabel = (provider: PoliticalTransaction["provider"]) => provider === "fmp" ? "FMP" : provider === "bargo" ? "Bargo" : "CapitolExposed";

export function PoliticalScoreCard({ summary }: { summary: PoliticalActivitySummary }) {
  const insufficient = summary.direction === "INSUFFICIENT_DATA";
  const unavailable = insufficient ? "—" : null;
  return <section className="ci-summary"><div className="ci-summary-copy"><span className="insight-badge">Public disclosures · {summary.period}</span><h1>POLITICAL ACTIVITY</h1><p>Quantitative view of publicly reported congressional transactions. Activity intensity is separate from market direction and is not an investment recommendation.</p>{insufficient && <p className="mt-3 text-sm"><strong>No provider-reported disclosures in this period.</strong> Absence is not treated as an officially verified zero.</p>}<div className="ci-summary-meta"><span className={`badge ${directionClass(summary.direction)}`}>{summary.direction.replaceAll("_", " ")}</span><span>{summary.confidence} CONFIDENCE</span><span>{insufficient ? "DATA UNAVAILABLE" : `${summary.dataCompleteness.toFixed(0)}% COVERAGE`}</span></div></div><div className="ci-gauge" style={{ "--score": `${insufficient ? 0 : summary.activityIntensityScore}%` } as React.CSSProperties}><div><strong>{unavailable ?? summary.activityIntensityScore.toFixed(0)}</strong>{!insufficient && <span>/100</span>}</div><small>ACTIVITY INTENSITY</small></div><div className="ci-summary-side"><div className="ci-metric"><span>Purchases</span><strong>{unavailable ?? summary.purchaseCount}</strong></div><div className="ci-metric"><span>Sales</span><strong>{unavailable ?? summary.saleCount}</strong></div><div className="ci-metric"><span>Unique members</span><strong>{unavailable ?? summary.uniquePoliticians}</strong></div><div className="ci-metric"><span>Latest disclosure</span><strong>{summary.lastDisclosureDate ?? "Unavailable"}</strong></div></div></section>;
}

export function PoliticalTransactionTable({ transactions }: { transactions: PoliticalTransaction[] }) {
  return <div className="table-shell overflow-x-auto"><table className="data-table min-w-[1180px]"><thead><tr><th>Disclosure</th><th>Transaction</th><th>Delay</th><th>Member</th><th>Chamber / party</th><th>Owner</th><th>Asset</th><th>Action</th><th>Amount range</th><th>Price / return</th><th>Source</th></tr></thead><tbody>{transactions.map((row) => { const currentReturn = row.priceAtDisclosure && row.currentPrice ? (row.currentPrice / row.priceAtDisclosure - 1) * 100 : null; return <tr key={row.id}><td><strong>{row.disclosureDate}</strong>{row.disclosureDelayDays > 45 && <small className="block text-amber-700">LATE DISCLOSURE</small>}</td><td>{row.transactionDate}</td><td>{row.disclosureDelayDays}d</td><td><Link href={`/politicians/${encodeURIComponent(row.politicianId)}`} className="font-bold text-indigo-700">{row.politicianName}</Link></td><td>{row.chamber}<small className="muted block">{row.party}</small></td><td>{row.ownerType}</td><td><strong>{row.symbol ?? row.assetName}</strong><small className="muted block">{row.assetName}</small></td><td><span className={`badge ${row.transactionType === "PURCHASE" ? "badge-buy" : row.transactionType.startsWith("SALE") ? "badge-sell" : "badge-hold"}`}>{row.transactionType.replaceAll("_", " ")}</span></td><td>{row.amountRangeRaw ?? "Not reported"}<small className="muted block">{row.amountMethod === "MIDPOINT_ESTIMATE" ? `Midpoint estimate ${politicalMoney(row.estimatedAmount ?? 0)}` : row.amountMethod}</small></td><td>{row.priceAtDisclosure ? `$${row.priceAtDisclosure.toFixed(2)}` : "—"}<small className={`block ${(currentReturn ?? 0) >= 0 ? "positive" : "negative"}`}>{currentReturn === null ? "Return unavailable" : `${currentReturn >= 0 ? "+" : ""}${currentReturn.toFixed(1)}% since disclosure`}</small></td><td>{row.sourceUrl ? <a href={row.sourceUrl} target="_blank" rel="noreferrer" className="text-indigo-700">{politicalProviderLabel(row.provider)} / filing ↗</a> : politicalProviderLabel(row.provider)}<small className="muted block">{row.verificationStatus.replaceAll("_", " ")}</small></td></tr>; })}{transactions.length === 0 && <tr><td colSpan={11} className="py-8 text-center muted">No provider-reported disclosures for this selection. Absence is not treated as an officially verified zero.</td></tr>}</tbody></table></div>;
}

export function PoliticalRanking({ title, rows }: { title: string; rows: PoliticalBreakdownRow[] }) {
  return <section className="card p-6"><h2 className="text-lg font-bold">{title}</h2><div className="mt-5 grid gap-3">{rows.slice(0, 8).map((row, index) => <div className="soft-card grid grid-cols-[30px_1fr_auto] items-center gap-3 p-3" key={row.key}><span className="muted">{index + 1}</span><div><strong>{row.label}</strong><small className="muted block">{row.uniquePoliticians} members · {row.purchaseCount} purchases · {row.saleCount} sales</small></div><span className={`badge ${directionClass(row.direction)}`}>{politicalMoney(row.estimatedActivity)}</span></div>)}{!rows.length && <p className="muted">No qualifying public disclosures for this filter.</p>}</div></section>;
}

export function PoliticalClusterList({ clusters }: { clusters: PoliticalCluster[] }) {
  return <div className="grid gap-3">{clusters.map((cluster) => <article className="soft-card p-4" key={cluster.id}><div className="section-row"><strong>{cluster.symbol ?? "Unresolved asset"} · CONGRESSIONAL {cluster.direction} CLUSTER</strong><span className={`badge ${cluster.direction === "PURCHASE" ? "badge-buy" : "badge-sell"}`}>{cluster.strength}</span></div><p className="muted mt-2 text-sm">{cluster.uniquePoliticians} independent members · {cluster.transactionCount} disclosures · {activityRange(0, cluster.estimatedAmount)} midpoint activity · {cluster.firstDisclosureDate} → {cluster.lastDisclosureDate}</p></article>)}{!clusters.length && <p className="muted">No multi-member cluster detected in the selected window.</p>}</div>;
}
