"use client";

import Link from "next/link";
import { ArrowDown, ArrowUp, FilePenLine, Plus, Trash2, X } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { formatCurrency, formatPercent } from "@/lib";
import { useMarketSearch } from "@/lib/use-market-search";
import type { AccountWatchlist, MarketQuoteDto, SearchInstrument } from "@/types";

type Envelope<T> = { data?: T; error?: { message?: string } };
const instrumentType = (type: SearchInstrument["type"]) => type === "Stock" ? "EQUITY" : type.toUpperCase();

export function WatchlistView() {
  const [lists, setLists] = useState<AccountWatchlist[]>([]); const [selectedId, setSelectedId] = useState("");
  const [modal, setModal] = useState(false); const [query, setQuery] = useState(""); const [filter, setFilter] = useState(""); const [sort, setSort] = useState<"position" | "symbol" | "change">("position"); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const { results, loading, error } = useMarketSearch(query, []); const selected = results[0];
  const load = useCallback(async () => { setBusy(true); setMessage(""); try { const response = await fetch("/api/account/watchlists", { cache: "no-store" }); const body = await response.json() as Envelope<AccountWatchlist[]>; if (!response.ok) throw new Error(body.error?.message ?? "Watchlist non disponibile"); setLists(body.data ?? []); setSelectedId((current) => current || body.data?.[0]?.id || ""); } catch (requestError) { setMessage(requestError instanceof Error ? requestError.message : "Watchlist non disponibile"); } finally { setBusy(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const current = lists.find((list) => list.id === selectedId) ?? lists[0];
  const pollingSymbols = [...new Set(lists.flatMap((list) => list.items.map((item) => item.symbol)))].join(",");
  useEffect(() => {
    const symbols = pollingSymbols.split(",").filter(Boolean);
    if (!symbols.length) return;
    let active = true; let timer: number | undefined;
    const refreshQuotes = async () => {
      if (document.hidden) { timer = window.setTimeout(refreshQuotes, 30_000); return; }
      try {
        const response = await fetch(`/api/market/quotes?symbols=${encodeURIComponent(symbols.join(","))}`, { cache: "no-store" });
        const body = await response.json() as Envelope<MarketQuoteDto[]> & { meta?: { provider?: string; sourceTimestamp?: string | null } };
        if (!response.ok || !active || !body.data) return;
        const quotes = new Map(body.data.map((quote) => [quote.symbol, quote]));
        setLists((existing) => existing.map((list) => ({ ...list, items: list.items.map((item) => { const quote = quotes.get(item.symbol); return quote ? { ...item, price: quote.price, changePercent: quote.changePercent, volume: quote.volume, marketState: quote.marketState, lastUpdated: quote.asOf ?? body.meta?.sourceTimestamp ?? new Date().toISOString(), provider: body.meta?.provider ?? item.provider } : item; }) })));
      } finally { if (active) timer = window.setTimeout(refreshQuotes, 20_000); }
    };
    const onVisibility = () => { if (!document.hidden) void refreshQuotes(); };
    timer = window.setTimeout(refreshQuotes, 15_000); document.addEventListener("visibilitychange", onVisibility);
    return () => { active = false; if (timer) window.clearTimeout(timer); document.removeEventListener("visibilitychange", onVisibility); };
  }, [pollingSymbols]);

  async function createList() { const name = window.prompt("Nome della nuova watchlist"); if (!name) return null; const response = await fetch("/api/account/watchlists", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); const body = await response.json() as Envelope<{ id: string }>; if (!response.ok) throw new Error(body.error?.message ?? "Creazione non riuscita"); await load(); setSelectedId(body.data?.id ?? ""); return body.data?.id ?? null; }
  async function renameList() { if (!current) return; const name = window.prompt("Nuovo nome", current.name); if (!name) return; const response = await fetch(`/api/account/watchlists/${current.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); const body = await response.json() as Envelope<unknown>; if (!response.ok) setMessage(body.error?.message ?? "Rinomina non riuscita"); await load(); }
  async function deleteList() { if (!current || !window.confirm(`Eliminare ${current.name}?`)) return; const response = await fetch(`/api/account/watchlists/${current.id}`, { method: "DELETE" }); const body = await response.json() as Envelope<unknown>; if (!response.ok) setMessage(body.error?.message ?? "Eliminazione non riuscita"); else setSelectedId(""); await load(); }
  async function editNote(itemId: string, currentNote: string | null) { if (!current) return; const notes = window.prompt("Nota personale", currentNote ?? ""); if (notes === null) return; const response = await fetch(`/api/account/watchlists/${current.id}/items/${itemId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ notes: notes || null }) }); const body = await response.json() as Envelope<unknown>; if (!response.ok) setMessage(body.error?.message ?? "Nota non salvata"); await load(); }
  async function move(itemId: string, direction: -1 | 1) { if (!current) return; const index = current.items.findIndex((item) => item.id === itemId); const peer = current.items[index + direction]; const item = current.items[index]; if (!peer || !item) return; const headers = { "Content-Type": "application/json" }; await Promise.all([fetch(`/api/account/watchlists/${current.id}/items/${item.id}`, { method: "PATCH", headers, body: JSON.stringify({ position: peer.position }) }), fetch(`/api/account/watchlists/${current.id}/items/${peer.id}`, { method: "PATCH", headers, body: JSON.stringify({ position: item.position }) })]); await load(); }
  async function add() { if (!selected || busy) return; setBusy(true); setMessage(""); try { const listId = current?.id ?? await createList(); if (!listId) return; const response = await fetch(`/api/account/watchlists/${listId}/items`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ symbol: selected.symbol, name: selected.name, type: instrumentType(selected.type), currency: selected.currency, market: selected.venue, position: current?.items.length ?? 0 }) }); const body = await response.json() as Envelope<unknown>; if (!response.ok) throw new Error(body.error?.message ?? "Inserimento non riuscito"); setModal(false); setQuery(""); await load(); } catch (requestError) { setMessage(requestError instanceof Error ? requestError.message : "Inserimento non riuscito"); } finally { setBusy(false); } }
  async function remove(itemId: string) { if (!current) return; setBusy(true); const response = await fetch(`/api/account/watchlists/${current.id}/items/${itemId}`, { method: "DELETE" }); const body = await response.json() as Envelope<unknown>; if (!response.ok) setMessage(body.error?.message ?? "Rimozione non riuscita"); await load(); }

  const displayRows = [...(current?.items ?? [])].filter((row) => `${row.symbol} ${row.name} ${row.notes ?? ""}`.toLowerCase().includes(filter.toLowerCase())).sort((a, b) => sort === "symbol" ? a.symbol.localeCompare(b.symbol) : sort === "change" ? (b.changePercent ?? -Infinity) - (a.changePercent ?? -Infinity) : a.position - b.position);
  return <div className="container-shell page-stack"><header className="section-row"><div><span className="page-kicker">Collections / Private workspace</span><h1 className="page-title">Your watchlists.</h1><p className="muted mt-3">Liste persistenti, quotazioni server-side e analisi quantitative esplicite.</p></div><div className="flex gap-2"><button className="button-secondary" onClick={() => void createList().catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Creazione non riuscita"))}><Plus size={17}/>New list</button><button className="button-primary" onClick={() => setModal(true)}><Plus size={17}/>Add instrument</button></div></header>
  {message && <section className="soft-card p-5"><strong>Workspace unavailable</strong><p className="muted mt-2">{message}</p>{message.toLowerCase().includes("autentic") && <Link className="button-primary mt-4 inline-flex" href="/login">Sign in</Link>}</section>}
  {lists.length > 0 && <div className="section-row"><div className="flex flex-wrap gap-2">{lists.map((list) => <button key={list.id} className={list.id === current?.id ? "button-primary" : "button-secondary"} onClick={() => setSelectedId(list.id)}>{list.name} · {list.items.length}</button>)}</div><div className="flex gap-2"><button className="button-secondary" onClick={() => void renameList()}><FilePenLine size={15}/>Rename</button><button className="button-secondary" onClick={() => void deleteList()}><Trash2 size={15}/>Delete</button></div></div>}
  {current && <div className="grid-2"><label className="small-label">Filter<input className="modal-input" value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Symbol, name or note"/></label><label className="small-label">Order<select className="modal-input" value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="position">Custom order</option><option value="symbol">Symbol</option><option value="change">Daily change</option></select></label></div>}
  {current?.items.some((item) => item.lastUpdated) && <p className="muted text-xs">Near-live quotes · {current.items.find((item) => item.provider)?.provider ?? "provider"} · last update {new Date(current.items.map((item) => item.lastUpdated).filter((value): value is string => Boolean(value)).sort().at(-1)!).toLocaleTimeString()} · polling pauses while this page is hidden.</p>}
  <section className="table-shell"><table className="data-table"><thead><tr><th>Symbol</th><th>Instrument</th><th>Price</th><th>Daily change</th><th>Signal / confidence</th><th>Target</th><th>Next event</th><th>Alerts</th><th/></tr></thead><tbody>{displayRows.map((row) => <tr key={row.id}><td><span className="table-symbol">{row.symbol.replace(/[^A-Z0-9]/g, "").slice(0, 2)}</span><strong>{row.symbol}</strong></td><td><Link href={`/instrument/${encodeURIComponent(row.market || "market")}/${encodeURIComponent(row.symbol.toLowerCase())}/overview`}>{row.name}</Link>{row.notes && <small className="muted block">{row.notes}</small>}</td><td className="font-bold">{row.price === null ? "Dato non disponibile" : formatCurrency(row.price, row.currency ?? "USD")}</td><td className={(row.changePercent ?? 0) >= 0 ? "positive" : "negative"}>{row.changePercent === null ? "—" : formatPercent(row.changePercent, true)}</td><td><span className={`badge ${row.signal?.includes("BUY") ? "badge-buy" : row.signal?.includes("SELL") ? "badge-sell" : "badge-hold"}`}>{row.signal ?? "N/A"}</span>{row.confidence !== null && <small className="muted ml-2">{Math.round(row.confidence * 100)}%</small>}</td><td>{row.target === null ? "—" : formatCurrency(row.target, row.currency ?? "USD")}</td><td>{row.nextEvent ? <><strong>{row.nextEvent.title}</strong><small className="muted block">{new Date(row.nextEvent.startsAt).toLocaleDateString()}</small></> : "—"}</td><td>{row.activeAlerts || "—"}</td><td><div className="flex gap-1"><button disabled={busy || sort !== "position"} className="icon-button !h-9 !w-9" onClick={() => void move(row.id, -1)} aria-label={`Move ${row.symbol} up`}><ArrowUp size={14}/></button><button disabled={busy || sort !== "position"} className="icon-button !h-9 !w-9" onClick={() => void move(row.id, 1)} aria-label={`Move ${row.symbol} down`}><ArrowDown size={14}/></button><button disabled={busy} className="icon-button !h-9 !w-9" onClick={() => void editNote(row.id, row.notes)} aria-label={`Edit note for ${row.symbol}`}><FilePenLine size={14}/></button><button disabled={busy} className="icon-button !h-9 !w-9" onClick={() => void remove(row.id)} aria-label={`Remove ${row.symbol}`}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table>{busy && !lists.length && <div className="p-12 text-center muted">Loading private workspace…</div>}{!busy && !displayRows.length && <div className="p-12 text-center muted">{current ? "No instruments match this view." : "Create your first private watchlist."}</div>}</section>
  {modal && <div className="modal-backdrop" onMouseDown={() => setModal(false)}><div className="modal-card card" onMouseDown={(event) => event.stopPropagation()}><div className="flex justify-between"><div><span className="page-kicker">Private collection</span><h2 className="mt-2 text-2xl font-bold">Add instrument</h2></div><button className="icon-button !h-9 !w-9" onClick={() => setModal(false)}><X size={18}/></button></div><label className="small-label mt-6 block">Symbol or company</label><input className="modal-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="AAPL, ENI.MI, Bitcoin…"/>{loading && <p className="muted mt-3">Searching…</p>}{error && <p className="negative mt-3">{error}</p>}{selected && <div className="soft-card mt-3 p-4"><strong>{selected.symbol} · {selected.name}</strong><small className="muted block">{selected.venue} · {selected.type}</small></div>}<label className="small-label mt-4 block">Watchlist</label><select className="modal-input" value={current?.id ?? ""} onChange={(event) => setSelectedId(event.target.value)}><option value="">Create one when adding</option>{lists.map((list) => <option value={list.id} key={list.id}>{list.name}</option>)}</select>{message && <p className="negative mt-3">{message}</p>}<button disabled={!selected || busy} className="button-primary mt-6 w-full" onClick={() => void add()}>{busy ? "Adding…" : "Add to watchlist"}</button></div></div>}</div>;
}
