"use client";

import { Area, Bar, CartesianGrid, ComposedChart, Legend, Line, ResponsiveContainer, Scatter, Tooltip, XAxis, YAxis } from "recharts";
import type { TooltipContentProps } from "recharts";
import type { MarketChartPoint, PoliticalTimelinePoint, PoliticalTransaction } from "@/types";

function side(row: PoliticalTransaction) { return row.transactionType === "PURCHASE" ? "PURCHASE" : row.transactionType.startsWith("SALE") ? "SALE" : "OTHER"; }

export function PoliticalPriceDisclosureChart({ prices, transactions }: { prices: MarketChartPoint[]; transactions: PoliticalTransaction[] }) {
  const priceByDate = new Map(prices.map((point) => [point.timestamp.slice(0, 10), point.close]));
  const nearest = (date: string) => { const exact = priceByDate.get(date); if (exact !== undefined) return exact; return prices.find((point) => point.timestamp.slice(0, 10) >= date)?.close ?? null; };
  const markers = transactions.flatMap((row) => [{ date: row.transactionDate, value: row.priceAtTransaction ?? nearest(row.transactionDate), marker: "T", phase: "Transaction date", row, side: side(row) }, { date: row.disclosureDate, value: row.priceAtDisclosure ?? nearest(row.disclosureDate), marker: "D", phase: "Disclosure date", row, side: side(row) }]).filter((item) => item.value !== null);
  const tooltip = ({ active, payload }: TooltipContentProps) => { const item = payload?.[0]?.payload as (typeof markers)[number] | undefined; if (!active || !item?.row) return null; return <div className="rounded-xl border border-slate-200 bg-white p-4 text-xs shadow-xl"><strong>{item.marker} · {item.phase}</strong><div className="mt-2 grid gap-1"><span>{item.row.politicianName} · {item.row.chamber} · {item.row.party}</span><span>{item.row.transactionType} · owner {item.row.ownerType}</span><span>Transaction {item.row.transactionDate}</span><span>Disclosure {item.row.disclosureDate} · delay {item.row.disclosureDelayDays}d</span><span>{item.row.amountRangeRaw ?? "Amount not reported"}</span><span>{item.row.source}</span></div></div>; };
  const chartData = prices.map((point) => ({ date: point.timestamp.slice(0, 10), value: point.close }));
  return <div className="h-[390px] w-full"><ResponsiveContainer><ComposedChart data={chartData} margin={{ top: 18, right: 16, left: 2, bottom: 8 }}><CartesianGrid vertical={false} stroke="#e7ebf2"/><XAxis dataKey="date" minTickGap={48} tick={{ fontSize: 11, fill: "#64748b" }}/><YAxis domain={["auto", "auto"]} tick={{ fontSize: 11, fill: "#64748b" }} width={68}/><Tooltip content={tooltip}/><Legend/><Line type="monotone" dataKey="value" name="Price" stroke="#6576ed" strokeWidth={2.5} dot={false}/><Scatter data={markers.filter((item) => item.marker === "T" && item.side === "PURCHASE")} dataKey="value" name="T · purchase" fill="#40d7a5" opacity={.45} shape="triangle"/><Scatter data={markers.filter((item) => item.marker === "T" && item.side === "SALE")} dataKey="value" name="T · sale" fill="#e95f75" opacity={.45} shape="triangle"/><Scatter data={markers.filter((item) => item.marker === "D" && item.side === "PURCHASE")} dataKey="value" name="D · purchase disclosure" fill="#0ea875" shape="triangle"/><Scatter data={markers.filter((item) => item.marker === "D" && item.side === "SALE")} dataKey="value" name="D · sale disclosure" fill="#d93f5a" shape="triangle"/></ComposedChart></ResponsiveContainer></div>;
}

export function PoliticalTimelineChart({ data }: { data: PoliticalTimelinePoint[] }) {
  return <div className="h-[320px] w-full"><ResponsiveContainer><ComposedChart data={data} margin={{ top: 10, right: 10, left: 0, bottom: 0 }}><defs><linearGradient id="politicalActivityFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#6576ed" stopOpacity={.22}/><stop offset="1" stopColor="#6576ed" stopOpacity={.02}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e7ebf2"/><XAxis dataKey="date" minTickGap={35} tick={{ fontSize: 11, fill: "#64748b" }}/><YAxis yAxisId="count" allowDecimals={false} tick={{ fontSize: 11, fill: "#64748b" }}/><YAxis yAxisId="amount" orientation="right" hide/><Tooltip/><Legend/><Area yAxisId="amount" dataKey="estimatedActivity" name="Estimated disclosed activity" stroke="#6576ed" fill="url(#politicalActivityFill)"/><Bar yAxisId="count" dataKey="purchases" name="Purchase disclosures" fill="#40d7a5" radius={[4,4,0,0]}/><Bar yAxisId="count" dataKey="sales" name="Sale disclosures" fill="#e95f75" radius={[4,4,0,0]}/></ComposedChart></ResponsiveContainer></div>;
}
