import { z } from "zod";
import { symbolSchema } from "./market";

export const accountIdSchema = z.uuid();
export const registerSchema = z.object({ name: z.string().trim().min(2).max(160), email: z.email().max(320).transform((value) => value.toLowerCase()), password: z.string().min(12).max(200) });
export const loginSchema = z.object({ email: z.email().max(320).transform((value) => value.toLowerCase()), password: z.string().min(1).max(200) });
export const watchlistCreateSchema = z.object({ name: z.string().trim().min(1).max(120), description: z.string().trim().max(1_000).nullable().optional() });
export const watchlistUpdateSchema = watchlistCreateSchema.partial().refine((value) => Object.keys(value).length > 0);
export const watchlistItemSchema = z.object({ symbol: symbolSchema, name: z.string().trim().min(1).max(300), type: z.enum(["EQUITY", "ETF", "FUND", "INDEX", "CRYPTO", "FOREX", "COMMODITY"]).default("EQUITY"), currency: z.string().trim().length(3).toUpperCase().optional(), market: z.string().trim().max(80).optional(), notes: z.string().trim().max(2_000).nullable().optional(), position: z.number().int().min(0).max(10_000).default(0) });
export const watchlistItemUpdateSchema = z.object({ notes: z.string().trim().max(2_000).nullable().optional(), position: z.number().int().min(0).max(10_000).optional() }).refine((value) => Object.keys(value).length > 0);
export const portfolioCreateSchema = z.object({ name: z.string().trim().min(1).max(120), baseCurrency: z.string().trim().length(3).toUpperCase().default("USD") });
export const portfolioUpdateSchema = portfolioCreateSchema.partial().refine((value) => Object.keys(value).length > 0);
export const portfolioTransactionSchema = z.object({ type: z.enum(["BUY", "SELL", "DEPOSIT", "WITHDRAWAL", "DIVIDEND", "FEE", "SPLIT"]), symbol: symbolSchema.nullable().optional(), name: z.string().trim().min(1).max(300).optional(), instrumentType: z.enum(["EQUITY", "ETF", "FUND", "INDEX", "CRYPTO", "FOREX", "COMMODITY"]).default("EQUITY"), executedAt: z.iso.datetime(), quantity: z.number().positive().max(1_000_000_000).nullable().optional(), price: z.number().nonnegative().max(1_000_000_000).nullable().optional(), fees: z.number().nonnegative().max(1_000_000).default(0), currency: z.string().trim().length(3).toUpperCase(), notes: z.string().trim().max(2_000).nullable().optional() }).refine((value) => !["BUY", "SELL", "DIVIDEND", "SPLIT"].includes(value.type) || Boolean(value.symbol && value.quantity), { message: "Strumento e quantità richiesti per questa transazione" }).refine((value) => !["BUY", "SELL"].includes(value.type) || value.price !== null && value.price !== undefined, { message: "Prezzo richiesto per acquisto o vendita" });
export const alertTypeSchema = z.enum(["PRICE_ABOVE", "PRICE_BELOW", "PERCENT_CHANGE", "VOLUME_ANOMALY", "RSI", "MACD_CROSS", "BREAKOUT", "BREAKDOWN", "NEW_SIGNAL", "SIGNAL_CHANGE", "TARGET_REACHED", "STOP_REACHED", "EARNINGS", "DIVIDEND", "HIGH_RELEVANCE_NEWS", "GEOPOLITICAL_EVENT", "PORTFOLIO_RISK", "POLITICAL_PURCHASE_DISCLOSURE", "POLITICAL_SALE_DISCLOSURE", "POLITICAL_CLUSTER", "POLITICAL_WATCHLIST_ACTIVITY", "POLITICAL_DIRECTION_CHANGE"]);
export const alertCreateSchema = z.object({ type: alertTypeSchema, symbol: symbolSchema.nullable().optional(), name: z.string().trim().min(1).max(300).optional(), threshold: z.number().finite().nullable().optional(), horizon: z.string().trim().max(32).nullable().optional(), expiresAt: z.iso.datetime().nullable().optional() });
export const alertUpdateSchema = z.object({ status: z.enum(["ACTIVE", "TRIGGERED", "PAUSED", "EXPIRED", "DISABLED"]).optional(), threshold: z.number().finite().nullable().optional(), expiresAt: z.iso.datetime().nullable().optional() }).refine((value) => Object.keys(value).length > 0);
