import Link from "next/link";
import { ArrowRight, CalendarDays, CircleDollarSign, Radar, Sparkles, Star, TrendingUp } from "lucide-react";
import { MainPriceChart } from "@/components/charts/market-charts";
import { financialDataService } from "@/services";
import { formatCurrency, formatPercent, instrumentPath } from "@/lib";

export default async function DashboardPage(){
  const data = await financialDataService.getDashboardData();
  return <div className="container-shell page-stack dashboard-page">
  <header className="dashboard-heading"><div><span className="page-kicker">Personal intelligence workspace</span><h1 className="page-title">Good afternoon, {data.greetingName}.</h1><p className="muted mt-3 text-base">Focus on what moved, what matters and what comes next.</p></div><Link className="button-primary" href="/search"><Radar size={17}/>Explore markets</Link></header>
  <section className="market-pulse"><div className="pulse-label"><i/><span>Market pulse</span><small>US session</small></div>{data.pulse.map(({ name, value, change }) => <div className="pulse-item" key={name}><span>{name}</span><strong>{value}</strong><small>{change}</small></div>)}</section>
  <section className="grid-3 metric-grid">{[
    ["Portfolio value", formatCurrency(data.portfolioValue, "USD", 0), `+${formatCurrency(data.monthlyPortfolioChange, "USD", 0)} this month`, CircleDollarSign, "mint"],
    ["Signal balance", data.signalSummary, `${data.constructivePercent}% constructive`, TrendingUp, "violet"],
    ["Upcoming events", `${data.upcomingEvents} this week`, `${data.spotlight.symbol} earnings in ${data.spotlight.earnings.daysUntil}d`, CalendarDays, "amber"],
  ].map(([label,value,sub,Icon,tone])=><article className={`metric-card ${tone}`} key={String(label)}><div className="metric-icon"><Icon size={20}/></div><div><span className="small-label">{String(label)}</span><div className="kpi mt-3">{String(value)}</div><p className="muted mt-2 text-xs">{String(sub)}</p></div><span className="metric-orbit"/></article>)}</section>
  <section className="dashboard-main grid gap-5 xl:grid-cols-[minmax(0,1.7fr)_390px]"><article className="card chart-card p-5 md:p-7"><div className="section-row"><div><span className="page-kicker">Spotlight / AI infrastructure</span><h2 className="mt-2 text-2xl font-bold tracking-tight">{data.spotlight.name} <span className="muted text-sm font-medium">{data.spotlight.symbol}</span></h2><p className="muted mt-1 text-xs">{formatCurrency(data.spotlight.quote.price)} · <span className="positive font-bold">{formatPercent(data.spotlight.quote.changePercent, true)} today</span></p></div><Link className="button-outline" href={instrumentPath(data.spotlight, "overview")}>Open workspace <ArrowRight size={16}/></Link></div><MainPriceChart data={data.spotlightSeries} referenceValue={data.spotlight.quote.price} compact/></article><aside className="card watchlist-card overflow-hidden"><div className="watchlist-head"><div><span className="page-kicker">Curated list</span><h2>Daily focus</h2></div><Star size={18}/></div>{data.watchlist.map((row,index)=><Link href={index===0?instrumentPath(data.spotlight, "overview"):"/search"} key={row.symbol} className="watchlist-row"><span className="watchlist-symbol">{row.symbol.slice(0,2)}</span><div><strong>{row.symbol}</strong><small>{row.name}</small></div><div><strong>{formatCurrency(row.price)}</strong><small className={row.changePercent>=0?"positive":"negative"}>{formatPercent(row.changePercent, true)}</small></div></Link>)}<Link href="/watchlists" className="watchlist-more">Open all watchlists <ArrowRight size={15}/></Link></aside></section>
  <section className="lens-brief"><div className="lens-brief-icon"><Sparkles/></div><div><span className="page-kicker">Kairo Lens · Morning brief</span><h2>{data.briefTitle}</h2><p>{data.briefBody}</p></div><Link className="button-outline" href={instrumentPath(data.spotlight, "news")}>Read briefing <ArrowRight size={16}/></Link></section>
</div>}
