"use client";
import Link from "next/link";
import { ArrowRight, Eye, EyeOff, Sparkles } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import type { BrandIdentity } from "@/types";

export function AuthForm({ mode, brand }: { mode: "login" | "register"; brand: BrandIdentity }) {
  const router=useRouter(); const [show,setShow]=useState(false); const [error,setError]=useState("");
  const submit=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);if(String(form.get("password")||"").length<6){setError("Use at least 6 characters for this demo.");return}router.push("/dashboard")};
  return <main className="auth-shell"><section className="auth-story"><Link href="/" className="brand"><span className="brand-mark"><span/></span><span className="brand-name"><strong>{brand.name}</strong><small>{brand.tagline}</small></span></Link><div className="auth-copy"><span className="page-kicker">A clearer market ritual</span><h1>See the signal.<br/><em>Skip the noise.</em></h1><p>Kairo brings price action, fundamentals, events and narrative into one calm, intentional workspace.</p><div className="auth-quote"><Sparkles size={18}/><span>Built as an independent static product concept with realistic mock data.</span></div></div><span className="auth-foot">Market intelligence, designed in Milan · 2026</span></section><section className="auth-form-side"><form onSubmit={submit} className="auth-form"><Link href="/" className="brand auth-mobile-brand"><span className="brand-mark"><span/></span><span className="brand-name"><strong>{brand.name}</strong><small>{brand.tagline}</small></span></Link><span className="page-kicker">{mode==="login"?"Welcome back":"New workspace"}</span><h2>{mode==="login"?"Enter Kairo.":"Create your account."}</h2><p className="muted">{mode==="login"?"Your market workspace is ready.":"Set up a private demo workspace in a few seconds."}</p>{mode==="register"&&<div className="mt-7 grid-2"><label>First name<input name="first" required placeholder="Sam"/></label><label>Last name<input name="last" required placeholder="Morgan"/></label></div>}<label className="mt-6 block">Email<input name="email" type="email" required placeholder="sam@example.test"/></label><label className="mt-5 block">Password<span className="password-field"><input name="password" type={show?"text":"password"} required defaultValue="kairo-demo"/><button type="button" onClick={()=>setShow(!show)} aria-label="Show password">{show?<EyeOff/>:<Eye/>}</button></span></label>{error&&<p role="alert" className="negative mt-4">{error}</p>}<button className="button-primary mt-7 w-full">{mode==="login"?"Enter workspace":"Create account"}<ArrowRight size={17}/></button><p className="mt-6 text-center muted">{mode==="login"?"New to Kairo? ":"Already have an account? "}<Link className="font-bold text-indigo-600" href={mode==="login"?"/register":"/login"}>{mode==="login"?"Create account":"Sign in"}</Link></p></form></section></main>;
}
